INSERT INTO organizacion_externa 
(nit, nombre, representante_legal, telefono, ubicacion, sector_economico, actividad_principal, id_creador) 
VALUES
('900567890-1', 'Nequi S.A.', 'Andrés Vásquez Franco', '+573001234567', 'Medellín, Antioquia', 'Servicios Financieros', 'Billetera digital y pagos electrónicos', 1),

('900765432-2', 'Daviplata S.A.', 'Javier Suárez', '+573109876543', 'Bogotá D.C.', 'Servicios Financieros', 'Transferencias y pagos digitales', 1),

('901234567-3', 'RappiPay S.A.S.', 'Felipe Villamarín', '+573165554321', 'Bogotá D.C.', 'Tecnología Financiera', 'Servicios financieros y fintech', 1),

('900876543-4', 'Movii S.A.', 'Hernando Rubio', '+573012223344', 'Bogotá D.C.', 'Fintech', 'Plataforma de pagos y billetera digital', 1),

('900123456-5', 'Nu Colombia S.A.S.', 'Catalina Bretón', '+573159988776', 'Bogotá D.C.', 'Servicios Financieros', 'Tarjetas de crédito digitales', 1),

('900654321-6', 'Banco de Bogotá', 'Alejandro Figueroa', '+576075500', 'Bogotá D.C.', 'Bancario', 'Servicios financieros y crédito', 1),

('900333222-7', 'Bancolombia S.A.', 'Juan Carlos Mora', '+576045109000', 'Medellín, Antioquia', 'Bancario', 'Servicios bancarios y de inversión', 1),

('901111222-8', 'Dale! (Grupo Aval)', 'Luis Carlos Sarmiento', '+573125557788', 'Bogotá D.C.', 'Fintech', 'Plataforma digital de pagos', 1),

('901234999-9', 'Tpaga S.A.S.', 'Andrés Gutiérrez', '+573208889990', 'Bogotá D.C.', 'Fintech', 'Pagos móviles y transferencias', 1),

('901000888-0', 'Powwi S.A.S.', 'María Camila Pérez', '+573157774455', 'Cali, Valle del Cauca', 'Tecnología Financiera', 'Servicios de pagos y recargas digitales', 1);


INSERT INTO instalacion (nombre, tipo, ubicacion, capacidad) VALUES
('Salon 111', 'Salon de clases', 'El edificio numero 1 en el piso 1 en el salon de clases 1', 25),
('Salon 112', 'Salon de clases', 'El edificio numero 1 en el piso 1 en el salon de clases 2', 25),
('Salon 113', 'Salon de clases', 'El edificio numero 1 en el piso 1 en el salon de clases 3', 25),
('Salon 114', 'Salon de clases', 'El edificio numero 1 en el piso 1 en el salon de clases 4', 25),
('Salon 115', 'Salon de clases', 'El edificio numero 1 en el piso 1 en el salon de clases 5', 25),
('Salon 116', 'Salon de clases', 'El edificio numero 1 en el piso 1 en el salon de clases 6', 25),
('Salon 121', 'Salon de clases', 'El edificio numero 1 en el piso 2 en el salon de clases 1', 25),
('Salon 122', 'Salon de clases', 'El edificio numero 1 en el piso 2 en el salon de clases 2', 25),
('Salon 123', 'Salon de clases', 'El edificio numero 1 en el piso 2 en el salon de clases 3', 25),
('Salon 124', 'Salon de clases', 'El edificio numero 1 en el piso 2 en el salon de clases 4', 25),
('Salon 125', 'Salon de clases', 'El edificio numero 1 en el piso 2 en el salon de clases 5', 25),
('Salon 126', 'Salon de clases', 'El edificio numero 1 en el piso 2 en el salon de clases 6', 25),
('Salon 131', 'Salon de clases', 'El edificio numero 1 en el piso 3 en el salon de clases 1', 25),
('Salon 132', 'Salon de clases', 'El edificio numero 1 en el piso 3 en el salon de clases 2', 25),
('Salon 133', 'Salon de clases', 'El edificio numero 1 en el piso 3 en el salon de clases 3', 25),
('Salon 134', 'Salon de clases', 'El edificio numero 1 en el piso 3 en el salon de clases 4', 25),
('Salon 135', 'Salon de clases', 'El edificio numero 1 en el piso 3 en el salon de clases 5', 25),
('Salon 136', 'Salon de clases', 'El edificio numero 1 en el piso 3 en el salon de clases 6', 25),
('Salon 141', 'Salon de clases', 'El edificio numero 1 en el piso 4 en el salon de clases 1', 25),
('Salon 142', 'Salon de clases', 'El edificio numero 1 en el piso 4 en el salon de clases 2', 25),
('Salon 143', 'Salon de clases', 'El edificio numero 1 en el piso 4 en el salon de clases 3', 25),
('Salon 144', 'Salon de clases', 'El edificio numero 1 en el piso 4 en el salon de clases 4', 25),
('Salon 145', 'Salon de clases', 'El edificio numero 1 en el piso 4 en el salon de clases 5', 25),
('Salon 146', 'Salon de clases', 'El edificio numero 1 en el piso 4 en el salon de clases 6', 25),
('Salon 211', 'Salon de clases', 'El edificio numero 2 en el piso 1 en el salon de clases 1', 25),
('Salon 212', 'Salon de clases', 'El edificio numero 2 en el piso 1 en el salon de clases 2', 25),
('Salon 213', 'Salon de clases', 'El edificio numero 2 en el piso 1 en el salon de clases 3', 25),
('Salon 214', 'Salon de clases', 'El edificio numero 2 en el piso 1 en el salon de clases 4', 25),
('Salon 215', 'Salon de clases', 'El edificio numero 2 en el piso 1 en el salon de clases 5', 25),
('Salon 216', 'Salon de clases', 'El edificio numero 2 en el piso 1 en el salon de clases 6', 25),
('Salon 221', 'Salon de clases', 'El edificio numero 2 en el piso 2 en el salon de clases 1', 25),
('Salon 222', 'Salon de clases', 'El edificio numero 2 en el piso 2 en el salon de clases 2', 25),
('Salon 223', 'Salon de clases', 'El edificio numero 2 en el piso 2 en el salon de clases 3', 25),
('Salon 224', 'Salon de clases', 'El edificio numero 2 en el piso 2 en el salon de clases 4', 25),
('Salon 225', 'Salon de clases', 'El edificio numero 2 en el piso 2 en el salon de clases 5', 25),
('Salon 226', 'Salon de clases', 'El edificio numero 2 en el piso 2 en el salon de clases 6', 25),
('Salon 231', 'Salon de clases', 'El edificio numero 2 en el piso 3 en el salon de clases 1', 25),
('Salon 232', 'Salon de clases', 'El edificio numero 2 en el piso 3 en el salon de clases 2', 25),
('Salon 233', 'Salon de clases', 'El edificio numero 2 en el piso 3 en el salon de clases 3', 25),
('Salon 234', 'Salon de clases', 'El edificio numero 2 en el piso 3 en el salon de clases 4', 25),
('Salon 235', 'Salon de clases', 'El edificio numero 2 en el piso 3 en el salon de clases 5', 25),
('Salon 236', 'Salon de clases', 'El edificio numero 2 en el piso 3 en el salon de clases 6', 25),
('Salon 241', 'Salon de clases', 'El edificio numero 2 en el piso 4 en el salon de clases 1', 25),
('Salon 242', 'Salon de clases', 'El edificio numero 2 en el piso 4 en el salon de clases 2', 25),
('Salon 243', 'Salon de clases', 'El edificio numero 2 en el piso 4 en el salon de clases 3', 25),
('Salon 244', 'Salon de clases', 'El edificio numero 2 en el piso 4 en el salon de clases 4', 25),
('Salon 245', 'Salon de clases', 'El edificio numero 2 en el piso 4 en el salon de clases 5', 25),
('Salon 246', 'Salon de clases', 'El edificio numero 2 en el piso 4 en el salon de clases 6', 25),
('Salon 311', 'Salon de clases', 'El edificio numero 3 en el piso 1 en el salon de clases 1', 25),
('Salon 312', 'Salon de clases', 'El edificio numero 3 en el piso 1 en el salon de clases 2', 25),
('Salon 313', 'Salon de clases', 'El edificio numero 3 en el piso 1 en el salon de clases 3', 25),
('Salon 314', 'Salon de clases', 'El edificio numero 3 en el piso 1 en el salon de clases 4', 25),
('Salon 315', 'Salon de clases', 'El edificio numero 3 en el piso 1 en el salon de clases 5', 25),
('Salon 316', 'Salon de clases', 'El edificio numero 3 en el piso 1 en el salon de clases 6', 25),
('Salon 321', 'Salon de clases', 'El edificio numero 3 en el piso 2 en el salon de clases 1', 25),
('Salon 322', 'Salon de clases', 'El edificio numero 3 en el piso 2 en el salon de clases 2', 25),
('Salon 323', 'Salon de clases', 'El edificio numero 3 en el piso 2 en el salon de clases 3', 25),
('Salon 324', 'Salon de clases', 'El edificio numero 3 en el piso 2 en el salon de clases 4', 25),
('Salon 325', 'Salon de clases', 'El edificio numero 3 en el piso 2 en el salon de clases 5', 25),
('Salon 326', 'Salon de clases', 'El edificio numero 3 en el piso 2 en el salon de clases 6', 25),
('Salon 331', 'Salon de clases', 'El edificio numero 3 en el piso 3 en el salon de clases 1', 25),
('Salon 332', 'Salon de clases', 'El edificio numero 3 en el piso 3 en el salon de clases 2', 25),
('Salon 333', 'Salon de clases', 'El edificio numero 3 en el piso 3 en el salon de clases 3', 25),
('Salon 334', 'Salon de clases', 'El edificio numero 3 en el piso 3 en el salon de clases 4', 25),
('Salon 335', 'Salon de clases', 'El edificio numero 3 en el piso 3 en el salon de clases 5', 25),
('Salon 336', 'Salon de clases', 'El edificio numero 3 en el piso 3 en el salon de clases 6', 25),
('Salon 341', 'Salon de clases', 'El edificio numero 3 en el piso 4 en el salon de clases 1', 25),
('Salon 342', 'Salon de clases', 'El edificio numero 3 en el piso 4 en el salon de clases 2', 25),
('Salon 343', 'Salon de clases', 'El edificio numero 3 en el piso 4 en el salon de clases 3', 25),
('Salon 344', 'Salon de clases', 'El edificio numero 3 en el piso 4 en el salon de clases 4', 25),
('Salon 345', 'Salon de clases', 'El edificio numero 3 en el piso 4 en el salon de clases 5', 25),
('Salon 346', 'Salon de clases', 'El edificio numero 3 en el piso 4 en el salon de clases 6', 25),
('Salon 411', 'Salon de clases', 'El edificio numero 4 en el piso 1 en el salon de clases 1', 25),
('Salon 412', 'Salon de clases', 'El edificio numero 4 en el piso 1 en el salon de clases 2', 25),
('Salon 413', 'Salon de clases', 'El edificio numero 4 en el piso 1 en el salon de clases 3', 25),
('Salon 414', 'Salon de clases', 'El edificio numero 4 en el piso 1 en el salon de clases 4', 25),
('Salon 415', 'Salon de clases', 'El edificio numero 4 en el piso 1 en el salon de clases 5', 25),
('Salon 416', 'Salon de clases', 'El edificio numero 4 en el piso 1 en el salon de clases 6', 25),
('Salon 421', 'Salon de clases', 'El edificio numero 4 en el piso 2 en el salon de clases 1', 25),
('Salon 422', 'Salon de clases', 'El edificio numero 4 en el piso 2 en el salon de clases 2', 25),
('Salon 423', 'Salon de clases', 'El edificio numero 4 en el piso 2 en el salon de clases 3', 25),
('Salon 424', 'Salon de clases', 'El edificio numero 4 en el piso 2 en el salon de clases 4', 25),
('Salon 425', 'Salon de clases', 'El edificio numero 4 en el piso 2 en el salon de clases 5', 25),
('Salon 426', 'Salon de clases', 'El edificio numero 4 en el piso 2 en el salon de clases 6', 25),
('Salon 431', 'Salon de clases', 'El edificio numero 4 en el piso 3 en el salon de clases 1', 25),
('Salon 432', 'Salon de clases', 'El edificio numero 4 en el piso 3 en el salon de clases 2', 25),
('Salon 433', 'Salon de clases', 'El edificio numero 4 en el piso 3 en el salon de clases 3', 25),
('Salon 434', 'Salon de clases', 'El edificio numero 4 en el piso 3 en el salon de clases 4', 25),
('Salon 435', 'Salon de clases', 'El edificio numero 4 en el piso 3 en el salon de clases 5', 25),
('Salon 436', 'Salon de clases', 'El edificio numero 4 en el piso 3 en el salon de clases 6', 25),
('Salon 441', 'Salon de clases', 'El edificio numero 4 en el piso 4 en el salon de clases 1', 25),
('Salon 442', 'Salon de clases', 'El edificio numero 4 en el piso 4 en el salon de clases 2', 25),
('Salon 443', 'Salon de clases', 'El edificio numero 4 en el piso 4 en el salon de clases 3', 25),
('Salon 444', 'Salon de clases', 'El edificio numero 4 en el piso 4 en el salon de clases 4', 25),
('Salon 445', 'Salon de clases', 'El edificio numero 4 en el piso 4 en el salon de clases 5', 25),
('Salon 446', 'Salon de clases', 'El edificio numero 4 en el piso 4 en el salon de clases 6', 25),
('Auditorio Indigo', 'Auditorio', 'Bloque 1 (junto a la cafeteria principal del primer piso)', 110),
('Auditorio Magenta', 'Auditorio', 'Bloque 1 (subiendo las escaleras del ala este en el segundo piso)', 85),
('Auditorio Verde', 'Auditorio', 'Bloque 1 (al fondo del pasillo central del primer piso)', 98),
('Auditorio Magenta', 'Auditorio', 'Bloque 2 (en el primer piso, acceso por el patio interior)', 115),
('Auditorio Purpura', 'Auditorio', 'Bloque 2 (al lado oeste del piso 2)', 77),
('Auditorio Cyan', 'Auditorio', 'Bloque 2 (frente a los ascensores del segundo piso)', 105),
('Biblioteca Central', 'Biblioteca', 'Bloque 1 en el piso 1 al lado norte', 50);